# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Wheel-Null
version:      0.01
version_from: lib/POE/Wheel/Null.pm
installdirs:  site
requires:
    POE:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
